name: V1CE Development Updates

on:
  push:
    branches: ['main']

jobs:
  publish_development_update:
    name: Publish Development Update
    type: update
    environment: development
    params:
      channel: development
      platform: all
