import React,{useCallback,useEffect,useRef,useState} from "react";
import {StyleSheet,Text,TouchableOpacity,View} from "react-native";

const COLS=20,ROWS=24,CELL=16,TICK_NORMAL=160,TICK_SLOW=280,POWERUP_DURATION=6000;
const POWERUPS={slow:{icon:"⏱",color:"#00B0FF",label:"SLOW"},multi:{icon:"✕2",color:"#FF6B00",label:"2X"}} as const;
const DIR={UP:{x:0,y:-1},DOWN:{x:0,y:1},LEFT:{x:-1,y:0},RIGHT:{x:1,y:0}} as const;
type P={x:number;y:number}; type Dir=P; type PowerType=keyof typeof POWERUPS; type Power=P&{type:PowerType};
type Particle=P&{vx:number;vy:number;life:number;maxLife:number;hue:number;size:number};
const rand=(n:number)=>Math.floor(Math.random()*n);
const freePos=(snake:P[],exclude:(P|undefined)[]=[]):P=>{let p:P;do{p={x:rand(COLS),y:rand(ROWS)}}while(snake.some(s=>s.x===p.x&&s.y===p.y)||exclude.some(e=>e&&e.x===p.x&&e.y===p.y));return p};
const initState=()=>{const snake=[{x:10,y:12},{x:9,y:12},{x:8,y:12}];return{snake,food:freePos(snake),score:0,dead:false,powerup:null as Power|null}};
const rainbowColors=["#FF0040","#FF6B00","#FFD700","#00E676","#00B0FF","#AA00FF","#FF0099"];

export default function SnakeGame(){
 const[state,setState]=useState(initState);const[started,setStarted]=useState(false);const[rainbow,setRainbow]=useState(false);
 const[slowActive,setSlowActive]=useState(false);const[multiActive,setMultiActive]=useState(false);
 const slowTimer=useRef<ReturnType<typeof setTimeout>|null>(null),multiTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const slowRef=useRef(false),multiRef=useRef(false),nextDir=useRef<Dir>(DIR.RIGHT),curDir=useRef<Dir>(DIR.RIGHT),startedRef=useRef(false);
 const particles=useRef<Particle[]>([]);const hue=useRef(0);const touchStart=useRef<P|null>(null);
 useEffect(()=>{slowRef.current=slowActive},[slowActive]);useEffect(()=>{multiRef.current=multiActive},[multiActive]);
 const activatePowerup=useCallback((type:PowerType)=>{if(type==="slow"){setSlowActive(true);slowRef.current=true;if(slowTimer.current)clearTimeout(slowTimer.current);slowTimer.current=setTimeout(()=>{setSlowActive(false);slowRef.current=false},POWERUP_DURATION)}else{setMultiActive(true);multiRef.current=true;if(multiTimer.current)clearTimeout(multiTimer.current);multiTimer.current=setTimeout(()=>{setMultiActive(false);multiRef.current=false},POWERUP_DURATION)}},[]);
 const spawnParticles=useCallback((x:number,y:number,tailX:number,tailY:number)=>{hue.current=(hue.current+18)%360;for(let i=0;i<4;i++){const a=Math.random()*Math.PI*2,s=.5+Math.random()*1.5;particles.current.push({x:x*CELL+CELL/2,y:y*CELL+CELL/2,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:12+Math.floor(Math.random()*8),maxLife:20,hue:(hue.current+i*40)%360,size:1.5+Math.random()*2.5})}for(let i=0;i<14;i++){const a=Math.random()*Math.PI*2,s=.8+Math.random()*3.5;particles.current.push({x:tailX*CELL+CELL/2,y:tailY*CELL+CELL/2,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:22+Math.floor(Math.random()*18),maxLife:40,hue:(hue.current+i*20)%360,size:3+Math.random()*5})}},[]);
 const tick=useCallback(()=>{particles.current=particles.current.map(p=>({...p,x:p.x+p.vx,y:p.y+p.vy,vy:p.vy+.08,life:p.life-1})).filter(p=>p.life>0);setState(prev=>{if(prev.dead)return prev;curDir.current=nextDir.current;const h=prev.snake[0],n={x:h.x+curDir.current.x,y:h.y+curDir.current.y};if(n.x<0||n.x>=COLS||n.y<0||n.y>=ROWS||prev.snake.some(s=>s.x===n.x&&s.y===n.y))return{...prev,dead:true};const ate=n.x===prev.food.x&&n.y===prev.food.y;const atePower=!!prev.powerup&&n.x===prev.powerup.x&&n.y===prev.powerup.y;const newSnake=[n,...prev.snake];if(!ate)newSnake.pop();const tail=prev.snake[prev.snake.length-1];spawnParticles(h.x,h.y,tail.x,tail.y);if(atePower&&prev.powerup)activatePowerup(prev.powerup.type);let newPower=prev.powerup;if(atePower)newPower=null;if(ate&&!newPower&&Math.random()<.3){const type:PowerType=Math.random()<.5?"slow":"multi";newPower={...freePos(newSnake,[prev.food]),type}}return{...prev,snake:newSnake,food:ate?freePos(newSnake,[newPower??undefined]):prev.food,score:prev.score+(ate?(multiRef.current?2:1):0),powerup:newPower}})},[activatePowerup,spawnParticles]);
 useEffect(()=>{if(!started)return;const id=setInterval(tick,slowActive?TICK_SLOW:TICK_NORMAL);return()=>clearInterval(id)},[started,slowActive,tick]);
 useEffect(()=>()=>{if(slowTimer.current)clearTimeout(slowTimer.current);if(multiTimer.current)clearTimeout(multiTimer.current)},[]);
 const changeDir=(d:Dir)=>{if(d.x===-curDir.current.x&&d.y===-curDir.current.y)return;nextDir.current=d;if(!startedRef.current){startedRef.current=true;setStarted(true)}};
 const restart=()=>{curDir.current=DIR.RIGHT;nextDir.current=DIR.RIGHT;startedRef.current=false;particles.current=[];if(slowTimer.current)clearTimeout(slowTimer.current);if(multiTimer.current)clearTimeout(multiTimer.current);setSlowActive(false);setMultiActive(false);slowRef.current=false;multiRef.current=false;setState(initState());setStarted(false)};
 const onTouchStart=(x:number,y:number)=>{touchStart.current={x,y}};const onTouchEnd=(x:number,y:number)=>{if(!touchStart.current)return;const dx=x-touchStart.current.x,dy=y-touchStart.current.y;touchStart.current=null;if(Math.abs(dx)<10&&Math.abs(dy)<10){const h=state.snake[0],ddx=x-(h.x*CELL+CELL/2),ddy=y-(h.y*CELL+CELL/2);changeDir(Math.abs(ddx)>Math.abs(ddy)?(ddx>0?DIR.RIGHT:DIR.LEFT):(ddy>0?DIR.DOWN:DIR.UP));return}changeDir(Math.abs(dx)>Math.abs(dy)?(dx>0?DIR.RIGHT:DIR.LEFT):(dy>0?DIR.DOWN:DIR.UP))};
 const{snake,food,score,dead,powerup}=state;
 return <View style={s.wrap}><View style={s.board} onTouchStart={e=>onTouchStart(e.nativeEvent.locationX,e.nativeEvent.locationY)} onTouchEnd={e=>onTouchEnd(e.nativeEvent.locationX,e.nativeEvent.locationY)}>
 {Array.from({length:COLS+1}).map((_,i)=><View key={"v"+i} style={[s.vline,{left:i*CELL}]}/>)}{Array.from({length:ROWS+1}).map((_,i)=><View key={"h"+i} style={[s.hline,{top:i*CELL}]}/>)}
 {snake.map((p,i)=><View key={i} style={[s.cell,{left:p.x*CELL,top:p.y*CELL,backgroundColor:rainbow?rainbowColors[i%rainbowColors.length]:(i===0?"#0a0a0a":"#333"),opacity:i===0?1:Math.max(.35,1-i*.03)}]}><Text style={{fontSize:i===0?11:8,color:rainbow?"#fff":i===0?"#fff":"#ccc"}}>{i===0?"■":"▪"}</Text></View>)}
 {particles.current.map((p,i)=><View key={"p"+i} style={[s.particle,{left:p.x,top:p.y,width:p.size,height:p.size,backgroundColor:rainbow?rainbowColors[i%rainbowColors.length]:"#0a0a0a",opacity:p.life/p.maxLife}]}/>)}
 <Text style={[s.food,{left:food.x*CELL,top:food.y*CELL}]}>$</Text>{powerup&&<Text style={[s.power,{left:powerup.x*CELL,top:powerup.y*CELL,color:POWERUPS[powerup.type].color}]}>{POWERUPS[powerup.type].icon}</Text>}
 {!started&&!dead&&<View style={s.overlay}><Text style={s.overlayTitle}>JAYWALKER</Text><View style={s.powerLegend}><Text>⏱ <Text style={{color:"#00B0FF"}}>SLOW</Text></Text><Text>✕2 <Text style={{color:"#FF6B00"}}>MULTI</Text></Text></View><Text style={s.small}>Collect power-ups for bonuses</Text><TouchableOpacity onPress={()=>{startedRef.current=true;setStarted(true)}} style={s.button}><Text style={s.buttonText}>START →</Text></TouchableOpacity></View>}
 {dead&&<View style={s.overlay}><Text style={s.x}>[ X ]</Text><Text style={s.overlayTitle}>GAME OVER</Text><Text style={s.small}>Score: {score}</Text><TouchableOpacity onPress={restart} style={s.button}><Text style={s.buttonText}>RETRY →</Text></TouchableOpacity></View>}
 </View><View style={s.footer}><Text style={s.score}>SCORE {score}</Text><TouchableOpacity onPress={()=>setRainbow(v=>!v)}><Text style={s.rainbow}>{rainbow?"RAINBOW ON":"RAINBOW"}</Text></TouchableOpacity></View><View style={s.controls}><TouchableOpacity onPress={()=>changeDir(DIR.LEFT)} style={s.control}><Text>←</Text></TouchableOpacity><View><TouchableOpacity onPress={()=>changeDir(DIR.UP)} style={s.control}><Text>↑</Text></TouchableOpacity><TouchableOpacity onPress={()=>changeDir(DIR.DOWN)} style={s.control}><Text>↓</Text></TouchableOpacity></View><TouchableOpacity onPress={()=>changeDir(DIR.RIGHT)} style={s.control}><Text>→</Text></TouchableOpacity></View></View>
}
const s=StyleSheet.create({wrap:{alignItems:"center",paddingVertical:10},board:{width:COLS*CELL,height:ROWS*CELL,borderWidth:2,borderColor:"#0a0a0a",backgroundColor:"#fff",position:"relative",overflow:"hidden"},cell:{position:"absolute",width:CELL,height:CELL,alignItems:"center",justifyContent:"center"},vline:{position:"absolute",top:0,bottom:0,width:1,backgroundColor:"#000",opacity:.1},hline:{position:"absolute",left:0,right:0,height:1,backgroundColor:"#000",opacity:.1},particle:{position:"absolute"},food:{position:"absolute",fontSize:14,fontWeight:"900",fontFamily:"SpaceMono_700Bold",color:"#0a0a0a",width:CELL,height:CELL,textAlign:"center"},power:{position:"absolute",fontSize:10,width:CELL,height:CELL,textAlign:"center"},overlay:{position:"absolute",left:0,top:0,right:0,bottom:0,backgroundColor:"rgba(247,247,247,.85)",alignItems:"center",justifyContent:"center",gap:10},overlayTitle:{fontSize:30,fontWeight:"900"},x:{fontSize:44,fontWeight:"900"},powerLegend:{flexDirection:"row",gap:18},small:{fontSize:10,letterSpacing:1,textTransform:"uppercase",textAlign:"center"},button:{backgroundColor:"#0a0a0a",paddingHorizontal:32,paddingVertical:12},buttonText:{color:"#fff",fontSize:18,fontWeight:"900",letterSpacing:2},footer:{width:COLS*CELL,flexDirection:"row",justifyContent:"space-between",marginTop:8},score:{fontWeight:"900",letterSpacing:2},rainbow:{fontSize:9,fontWeight:"900",letterSpacing:2},controls:{flexDirection:"row",alignItems:"center",gap:10,marginTop:12},control:{width:44,height:36,borderWidth:2,borderColor:"#0a0a0a",alignItems:"center",justifyContent:"center",marginVertical:2}});